/**
 * Vaultic IDL bundle — wired to the deployed Anchor program.
 *
 * Source of truth:
 *   - JSON: `vaultic-contracts/target/idl/vaultic.json`, generated by `anchor build`
 *   - TS types: `vaultic-contracts/target/types/vaultic.ts`, generated alongside
 *
 * Both files are vendored into `src/idl/` so the backend can be built and
 * tested without a sibling dependency on the contract's `target/`
 * directory. Re-vendor whenever the on-chain program is re-deployed with
 * a changed instruction / account / event surface.
 *
 * Vendoring workflow (executed on each contract change):
 *   1. Run `anchor build` in `vaultic-contracts/`
 *   2. `cp vaultic-contracts/target/idl/vaultic.json vaultic-backend/src/idl/`
 *   3. `cp vaultic-contracts/target/types/vaultic.ts vaultic-backend/src/idl/vaultic-types.ts`
 *   4. `pnpm --filter vaultic-backend typecheck` to confirm the generated
 *      types still match call sites.
 *
 * Program deployment metadata lives in `vaultic-contracts/.env.deployed`.
 * Deployed to devnet: 2026-05-07
 * Program id: `5igWLTbdAjGfAZKsK9G3Buhe7mkrgC3GEYkQaD4PrTnZ`
 * Deploy signature: `2yhgpH5W7KhYuugUCn4QHC5kQkZrKhBcKHFCwtb1WAHLT7Mn5TEXbZy65FdssQgdjxjxPPjuE9X7djwEYJtb4MXn`
 */
import rawIdl from './vaultic.json';

// The `Vaultic` type alias is the strongly-typed IDL from Anchor's codegen.
// Every event / account / instruction in the program surfaces here with its
// exact Borsh shape, so `Program<Vaultic>` gives fully-typed `program.account.*`,
// `program.methods.*`, and `program.addEventListener(name, ...)` surfaces.
export type { Vaultic } from './vaultic-types';

// The actual runtime IDL is the JSON emitted by `anchor build`. We import
// it once here so other modules don't have to repeat the JSON import path.
import type { Vaultic } from './vaultic-types';
export const IDL = rawIdl as unknown as Vaultic;

/** Program id declared by `vaultic-contracts/programs/vaultic/src/lib.rs`. */
export const VAULTIC_PROGRAM_ADDRESS =
  '5igWLTbdAjGfAZKsK9G3Buhe7mkrgC3GEYkQaD4PrTnZ';

/**
 * Names of the nine events the backend listens for (design §3.1.4).
 * Kept as a `const` tuple so downstream dispatchers can exhaustively
 * switch on a union type without stringly-typed lookups.
 *
 * Note: `SalaryRevealed` and `DecryptionRequested` are also emitted by
 * the program (ten events total — see `events.rs`), but they're
 * deliberately omitted from this list because the backend does not
 * project them into domain tables; they surface to the frontend
 * directly via the raw SSE hub.
 */
export const VAULTIC_EVENT_NAMES = [
  'TreasuryInitialized',
  'EmployeeRegistered',
  'EmployeeTerminated',
  'PayrollExecutionStarted',
  'PayrollExecutionCompleted',
  'FHEComputationRequested',
  'IkaSigningRequested',
  'ClaimSubmitted',
  'ClaimProcessed',
] as const;

/** Literal union of every event name in {@link VAULTIC_EVENT_NAMES}. */
export type VaulticEventName = (typeof VAULTIC_EVENT_NAMES)[number];
